export const SET_PANEL_POSITION = 'SET_PANEL_POSITION';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const UPDATE_FONTS_LOADED = 'UPDATE_FONTS_LOADED';
export const UPDATE_FOCUSED_CLIENT = 'UPDATE_FOCUSED_CLIENT';
